### ISSUE TITLE
表情包制作和头像包安装后运行失败

### ISSUE THREAD

**Issue by cyberaltoria** [zhenxun-org/nonebot_plugins_zhenxun_bot#116]
## 插件名

zhenxun_plugin_petpet   zhenxun_plugin_memes

## GitHub 地址

您的插件的 GitHub 地址

## 备注
表清包制作和头像表情包

## 下载地址（可选）

您插件的下载地址，必须为 GitHub Release 地址

**Comment by cyberaltoria** [comment]
两者都显示缺失imageio，但是我在cmd已经安装了相应的环境

**Comment by cyberaltoria** [comment]
File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-qN34kHq3-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 194, in exec_module
    super().exec_module(module)
                        └ <module 'extensive_plugin.zhenxun_plugin_memes' from 'D:\\腾讯文件\\3297000763\\FileRecv\\下载文件\\1\\zhenxun_bot-main\\extensive_pl...

  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "D:\腾讯文件\3297000763\FileRecv\下载文件\1\zhenxun_bot-main\extensive_plugin\zhenxun_plugin_memes\__init__.py", line 13, in <module>
    from .data_source import memes

  File "D:\腾讯文件\3297000763\FileRecv\下载文件\1\zhenxun_bot-main\extensive_plugin\zhenxun_plugin_memes\data_source.py", line 1, in <module>
    from .utils import Meme, GifMeme

  File "D:\腾讯文件\3297000763\FileRecv\下载文件\1\zhenxun_bot-main\extensive_plugin\zhenxun_plugin_memes\utils.py", line 1, in <module>
    import imageio

ModuleNotFoundError: No module named 'imageio'
07-08 16:44:18 [ERROR] nonebot | Failed to import "zhenxun_plugin_petpet"
Traceback (most recent call last):

  File "D:\腾讯文件\3297000763\FileRecv\下载文件\1\zhenxun_bot-main\bot.py", line 15, in <module>
    nonebot.load_plugins("extensive_plugin")
    │       └ <function load_plugins at 0x000001BA6A2EC160>
    └ <module 'nonebot' from 'C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot-qN34kHq3-py3.9\\l...

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-qN34kHq3-py3.9\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
           │       └ <function PluginManager.load_all_plugins at 0x000001BA6A2DDD30>
           └ <nonebot.plugin.manager.PluginManager object at 0x000001BA6B96FEE0>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-qN34kHq3-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 128, in load_all_plugins
    return set(

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-qN34kHq3-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
                  │    │           │         │       │    └ <function PluginManager.list_plugins at 0x000001BA6A2DDC10>
                  │    │           │         │       └ <nonebot.plugin.manager.PluginManager object at 0x000001BA6B96FEE0>
                  │    │           │         └ 'zhenxun_plugin_petpet'
                  │    │           └ 'zhenxun_plugin_petpet'
                  │    └ <function PluginManager.load_plugin at 0x000001BA6A2DDCA0>
                  └ <nonebot.plugin.manager.PluginManager object at 0x000001BA6B96FEE0>

> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-qN34kHq3-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 106, in load_plugin
    module = importlib.import_module(
             │         └ <function import_module at 0x000001BA675580D0>
             └ <module 'importlib' from 'D:\\Program Files\\Python39\\lib\\importlib\\__init__.py'>

  File "D:\Program Files\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'extensive_plugin.zhenxun_plugin_petpet'
           │          └ <function _gcd_import at 0x000001BA670313A0>
           └ <module 'importlib._bootstrap' (frozen)>

  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-qN34kHq3-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 194, in exec_module
    super().exec_module(module)
                        └ <module 'extensive_plugin.zhenxun_plugin_petpet' from 'D:\\腾讯文件\\3297000763\\FileRecv\\下载文件\\1\\zhenxun_bot-main\\extensive_p...

  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "D:\腾讯文件\3297000763\FileRecv\下载文件\1\zhenxun_bot-main\extensive_plugin\zhenxun_plugin_petpet\__init__.py", line 12, in <module>
    from .data_source import commands

  File "D:\腾讯文件\3297000763\FileRecv\下载文件\1\zhenxun_bot-main\extensive_plugin\zhenxun_plugin_petpet\data_source.py", line 1, in <module>
    from .utils import Command

  File "D:\腾讯文件\3297000763\FileRecv\下载文件\1\zhenxun_bot-main\extensive_plugin\zhenxun_plugin_petpet\utils.py", line 3, in <module>
    import imageio

ModuleNotFoundError: No module named 'imageio'
07-08 16:44:27 [ERROR] uvicorn | [Errno 10048] error while attempting to bind on address ('127.0.0.1', 8080): 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。
07-08 16:47:30 [ERROR] nonebot | Failed to import "zhenxun_plugin_memes"
Traceback (most recent call last):

  File "D:\腾讯文件\3297000763\FileRecv\下载文件\1\zhenxun_bot-main\bot.py", line 15, in <module>
    nonebot.load_plugins("extensive_plugin")
    │       └ <function load_plugins at 0x000001D37A55C160>
    └ <module 'nonebot' from 'C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot-qN34kHq3-py3.9\\l...

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-qN34kHq3-py3.9\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
           │       └ <function PluginManager.load_all_plugins at 0x000001D37A54DD30>
           └ <nonebot.plugin.manager.PluginManager object at 0x000001D316C19C40>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-qN34kHq3-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 128, in load_all_plugins
    return set(

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-qN34kHq3-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
                  │    │           │         │       │    └ <function PluginManager.list_plugins at 0x000001D37A54DC10>
                  │    │           │         │       └ <nonebot.plugin.manager.PluginManager object at 0x000001D316C19C40>
                  │    │           │         └ 'zhenxun_plugin_memes'
                  │    │           └ 'zhenxun_plugin_memes'
                  │    └ <function PluginManager.load_plugin at 0x000001D37A54DCA0>
                  └ <nonebot.plugin.manager.PluginManager object at 0x000001D316C19C40>

> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-qN34kHq3-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 106, in load_plugin
    module = importlib.import_module(
             │         └ <function import_module at 0x000001D3777B80D0>
             └ <module 'importlib' from 'D:\\Program Files\\Python39\\lib\\importlib\\__init__.py'>

  File "D:\Program Files\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'extensive_plugin.zhenxun_plugin_memes'
           │          └ <function _gcd_import at 0x000001D3776013A0>
           └ <module 'importlib._bootstrap' (frozen)>

  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-qN34kHq3-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 194, in exec_module
    super().exec_module(module)
                        └ <module 'extensive_plugin.zhenxun_plugin_memes' from 'D:\\腾讯文件\\3297000763\\FileRecv\\下载文件\\1\\zhenxun_bot-main\\extensive_pl...

  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "D:\腾讯文件\3297000763\FileRecv\下载文件\1\zhenxun_bot-main\extensive_plugin\zhenxun_plugin_memes\__init__.py", line 13, in <module>
    from .data_source import memes

  File "D:\腾讯文件\3297000763\FileRecv\下载文件\1\zhenxun_bot-main\extensive_plugin\zhenxun_plugin_memes\data_source.py", line 1, in <module>
    from .utils import Meme, GifMeme

  File "D:\腾讯文件\3297000763\FileRecv\下载文件\1\zhenxun_bot-main\extensive_plugin\zhenxun_plugin_memes\utils.py", line 1, in <module>
    import imageio

ModuleNotFoundError: No module named 'imageio'
07-08 16:47:31 [ERROR] nonebot | Failed to import "zhenxun_plugin_petpet"
Traceback (most recent call last):

  File "D:\腾讯文件\3297000763\FileRecv\下载文件\1\zhenxun_bot-main\bot.py", line 15, in <module>
    nonebot.load_plugins("extensive_plugin")
    │       └ <function load_plugins at 0x000001D37A55C160>
    └ <module 'nonebot' from 'C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot-qN34kHq3-py3.9\\l...

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-qN34kHq3-py3.9\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
           │       └ <function PluginManager.load_all_plugins at 0x000001D37A54DD30>
           └ <nonebot.plugin.manager.PluginManager object at 0x000001D316C19C40>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-qN34kHq3-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 128, in load_all_plugins
    return set(

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-qN34kHq3-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
                  │    │           │         │       │    └ <function PluginManager.list_plugins at 0x000001D37A54DC10>
                  │    │           │         │       └ <nonebot.plugin.manager.PluginManager object at 0x000001D316C19C40>
                  │    │           │         └ 'zhenxun_plugin_petpet'
                  │    │           └ 'zhenxun_plugin_petpet'
                  │    └ <function PluginManager.load_plugin at 0x000001D37A54DCA0>
                  └ <nonebot.plugin.manager.PluginManager object at 0x000001D316C19C40>

> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-qN34kHq3-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 106, in load_plugin
    module = importlib.import_module(
             │         └ <function import_module at 0x000001D3777B80D0>
             └ <module 'importlib' from 'D:\\Program Files\\Python39\\lib\\importlib\\__init__.py'>

  File "D:\Program Files\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'extensive_plugin.zhenxun_plugin_petpet'
           │          └ <function _gcd_import at 0x000001D3776013A0>
           └ <module 'importlib._bootstrap' (frozen)>

  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-qN34kHq3-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 194, in exec_module
    super().exec_module(module)
                        └ <module 'extensive_plugin.zhenxun_plugin_petpet' from 'D:\\腾讯文件\\3297000763\\FileRecv\\下载文件\\1\\zhenxun_bot-main\\extensive_p...

  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "D:\腾讯文件\3297000763\FileRecv\下载文件\1\zhenxun_bot-main\extensive_plugin\zhenxun_plugin_petpet\__init__.py", line 12, in <module>
    from .data_source import commands

  File "D:\腾讯文件\3297000763\FileRecv\下载文件\1\zhenxun_bot-main\extensive_plugin\zhenxun_plugin_petpet\data_source.py", line 1, in <module>
    from .utils import Command

  File "D:\腾讯文件\3297000763\FileRecv\下载文件\1\zhenxun_bot-main\extensive_plugin\zhenxun_plugin_petpet\utils.py", line 3, in <module>
    import imageio

ModuleNotFoundError: No module named 'imageio'

**Comment by cyberaltoria** [comment]
这些是报错代码，大佬们可以给我看看我还缺失了什么吗

**Comment by Terli** [comment]
先进虚拟环境然后pip install imageio了吗
