### ISSUE TITLE
超分插件安装依赖出现问题

### ISSUE THREAD

**Issue by DuXinyu0722** [zhenxun-org/nonebot_plugins_zhenxun_bot#117]
系统版本：Windows 10 企业版 LTSC
真寻版本：v0.1.6.1
错误截图：
![image](https://user-images.githubusercontent.com/96709723/179188469-4ca953a5-180f-473f-adc0-325833c3b61d.png)
手动将提示的两个文件再升级后调用超分，仍然会报错，错误日志如下：
Running matcher <Matcher from extensive_plugin.super_resolution, type=message, priority=0, temp=True> failed.
Traceback (most recent call last):
  File "bot.py", line 21, in <module>
    nonebot.run()
  File "C:\Users\dxy\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Z1GDdidx-py3.8\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\dxy\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Z1GDdidx-py3.8\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "C:\Users\dxy\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Z1GDdidx-py3.8\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "C:\Users\dxy\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Z1GDdidx-py3.8\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\users\dxy\appdata\local\programs\python\python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\users\dxy\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "c:\users\dxy\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\dxy\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\dxy\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\dxy\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\dxy\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Z1GDdidx-py3.8\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\dxy\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Z1GDdidx-py3.8\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\dxy\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Z1GDdidx-py3.8\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\dxy\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Z1GDdidx-py3.8\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
    await handler(
  File "C:\Users\dxy\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Z1GDdidx-py3.8\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "D:\robot\zhenxun_bot\extensive_plugin\super_resolution\__init__.py", line 186, in _
    image_array: np.ndarray = image.__array__()
  File "C:\Users\dxy\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Z1GDdidx-py3.8\lib\site-packages\PIL\Image.py", line 517, in __getattr__
    raise AttributeError(name)
AttributeError: __array__

麻烦大佬看看这个是什么原因，插件加载是成功的，还有就是依赖那块为什么会吧我符合条件的依赖卸了装个不符合的。

**Comment by shinianj** [comment]
那个可能是pypi依赖那边的问题
