### ISSUE TITLE
小白提问：60s插件TypeError

### ISSUE THREAD

**Issue by CaffuChin0** [zhenxun-org/nonebot_plugins_zhenxun_bot#171]
02-14 09:05:30 [ERROR] nonebot | Failed to import "read_60s"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\zhenxun_bot\bot.py", line 14, in <module>
    nonebot.load_plugins("plugins")
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-7NSuiggF-py3.9\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-7NSuiggF-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 172, in load_all_plugins
    return set(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-7NSuiggF-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-7NSuiggF-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "C:\Users\Administrator\Desktop\Python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-7NSuiggF-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\zhenxun_bot\plugins\read_60s\__init__.py", line 71, in <module>
    scheduler.add_job(read60s, "cron", hour=time.hour, minute=time.minute, id=str(index))
**TypeError: __call__() takes 2 positional arguments but 3 were given**

env.dev已填
# 60s读世界
read_qq_friends=["xxx"] #设定要发送的QQ好友
read_qq_groups=["xxx", "xxx"] #设定要发送的群
read_inform_time=[{"HOUR":9,"MINUTE":1}] #设定要发送的时间

时间到了依旧不出60s读世界消息

**Comment by CaffuChin0** [comment]
已解决：
更新一下apscheduler库的版本
pip install nonebot-plugin-apscheduler
