### ISSUE TITLE
插件安装问题

### ISSUE THREAD

**Issue by ghost** [zhenxun-org/nonebot_plugins_zhenxun_bot#27]
大佬，这些个插件怎么安装到真寻里啊？我把插件目录放到/home/zhenxun_bot/plugins文件夹下，然后重启zhenxun，但是config.yaml中无相关配置，而且新增的插件也无法使用。

**Comment by AkashiCoin** [comment]
> 大佬，这些个插件怎么安装到真寻里啊？我把插件目录放到/home/zhenxun_bot/plugins文件夹下，然后重启zhenxun，但是config.yaml中无相关配置，而且新增的插件也无法使用。

仓库里一个文件夹代表一个插件，如果需要可以将插件的文件夹放到`/home/zhenxun_bot/plugins`文件夹下，然后重启

**Comment by eachbol2333** [comment]
同问，config.yam不生成配置，而且安装时两个命令都会出错
![image](https://user-images.githubusercontent.com/105063888/169323896-8afb6a36-5b63-492c-b51d-a70861a73f48.png)
![image](https://user-images.githubusercontent.com/105063888/169324287-81519d33-4309-4cb2-85c8-baf17811f8db.png)

**Comment by yj854231078** [comment]
我的插件安装还是不生效，已经把插件的文件夹添加进/home/zhenxun_bot/plugins下了，重启zhengxun甚至重启服务器都没有生效。。。

**Comment by yj854231078** [comment]
> 

大佬，还是不太行啊，重启zhenxun或者重启服务器再重启zhenxun配置文件中无配置，命令也不生效。

**Comment by yj854231078** [comment]
我找到问题了，缺少一些依赖没有安装，找错误可以去log下的日志文件，日志里明确记录报什么错误。

**Comment by eachbol2333** [comment]
大佬你是缺少什么依赖，我看了一堆看不出个所以然

**Comment by yj854231078** [comment]
> 大佬你是缺少什么依赖，我看了一堆看不出个所以然

他这每个插件文件夹放到/home/zhenxun_bot/plugins以后，重新启动真寻然后去log中的日志和错误日志查看错误，缺少相关的依赖有写。例如：ModuleNotFoundError: No module named 'nonebot_plugin_htmlrender'，你只需要去命令号运行pip install nonebot_plugin_htmlrender，或者pip2 install nonebot_plugin_htmlrender，或者pip3 install nonebot_plugin_htmlrender，然后重新运行zhenxun，看看日志文件中有没有显示你加载的插件名。

**Comment by eachbol2333** [comment]
不行，我感觉是版本的问题，我安装过了也会报错
![image](https://user-images.githubusercontent.com/105063888/169637902-e5cdee7e-9a91-4f6f-b18f-a2884e60164c.png)

**Comment by lightbearer1** [comment]
> 

请问大佬，我在执行pip install nonebot_plugin_htmlrender安装依赖后启动项目就会开始报错，卸载这个依赖后就恢复正常，可以麻烦您帮忙看看是什么出问题了么
05-23 14:02:12 [WARNING] plugins | azur_up_char 解析出错
05-23 14:02:13 [WARNING] plugins | prts_up_char 解析出错
Task exception was never retrieved
future: <Task finished name='Task-301' coro=<Connection.run() done, defined at C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\playwright\_impl\_connection.py:174> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\playwright\_impl\_connection.py", line 181, in run
    await self._transport.connect()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\playwright\_impl\_transport.py", line 136, in connect
    raise exc
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\playwright\_impl\_transport.py", line 124, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\asyncio\base_events.py", line 1676, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
05-23 14:02:13 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\starlette\routing.py", line 621, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\starlette\routing.py", line 518, in __aenter__
    await self._router.startup()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\starlette\routing.py", line 598, in startup
    await handler()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\nonebot_plugin_htmlrender\__init__.py", line 27, in init
    browser = await get_browser(**kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 40, in get_browser
    return _browser or await init(**kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 26, in init
    _playwright = await async_playwright().start()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\playwright\async_api\_context_manager.py", line 51, in start
    return await self.__aenter__()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\playwright\_impl\_connection.py", line 181, in run
    await self._transport.connect()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\playwright\_impl\_transport.py", line 136, in connect
    raise exc
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\playwright\_impl\_transport.py", line 124, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\asyncio\base_events.py", line 1676, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

05-23 14:02:13 [ERROR] uvicorn | Application startup failed. Exiting.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\bilibili_api\utils\network.py", line 26, in __clean
    loop = asyncio.get_event_loop()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\asyncio\events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.

**Comment by shinianj** [comment]
> > 
> 
> 请问大佬，我在执行pip install nonebot_plugin_htmlrender安装依赖后启动项目就会开始报错，卸载这个依赖后就恢复正常，可以麻烦您帮忙看看是什么出问题了么 05-23 14:02:12 [WARNING] plugins | azur_up_char 解析出错 05-23 14:02:13 [WARNING] plugins | prts_up_char 解析出错 Task exception was never retrieved future: <Task finished name='Task-301' coro=<Connection.run() done, defined at C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\playwright_impl_connection.py:174> exception=NotImplementedError()> Traceback (most recent call last): File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\playwright_impl_connection.py", line 181, in run await self._transport.connect() File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\playwright_impl_transport.py", line 136, in connect raise exc File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\playwright_impl_transport.py", line 124, in connect self._proc = await asyncio.create_subprocess_exec( File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec transport, protocol = await loop.subprocess_exec( File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\asyncio\base_events.py", line 1676, in subprocess_exec transport = await self._make_subprocess_transport( File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport raise NotImplementedError NotImplementedError 05-23 14:02:13 [ERROR] uvicorn | Traceback (most recent call last): File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\starlette\routing.py", line 621, in lifespan async with self.lifespan_context(app): File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\starlette\routing.py", line 518, in **aenter** await self._router.startup() File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\starlette\routing.py", line 598, in startup await handler() File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\nonebot_plugin_htmlrender__init__.py", line 27, in init browser = await get_browser(**kwargs) File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 40, in get_browser return _browser or await init(**kwargs) File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 26, in init _playwright = await async_playwright().start() File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\playwright\async_api_context_manager.py", line 51, in start return await self.**aenter**() File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\playwright\async_api_context_manager.py", line 46, in **aenter** playwright = AsyncPlaywright(next(iter(done)).result()) File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\playwright_impl_connection.py", line 181, in run await self._transport.connect() File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\playwright_impl_transport.py", line 136, in connect raise exc File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\playwright_impl_transport.py", line 124, in connect self._proc = await asyncio.create_subprocess_exec( File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec transport, protocol = await loop.subprocess_exec( File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\asyncio\base_events.py", line 1676, in subprocess_exec transport = await self._make_subprocess_transport( File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport raise NotImplementedError NotImplementedError
> 
> 05-23 14:02:13 [ERROR] uvicorn | Application startup failed. Exiting. Error in atexit._run_exitfuncs: Traceback (most recent call last): File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\bilibili_api\utils\network.py", line 26, in __clean loop = asyncio.get_event_loop() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\asyncio\events.py", line 642, in get_event_loop raise RuntimeError('There is no current event loop in thread %r.' RuntimeError: There is no current event loop in thread 'MainThread'.

win暂时无法使用这个（据我的经验来说是这样的）
