### ISSUE TITLE
还是mockingbird网络和下载问题

### ISSUE THREAD

**Issue by milkasir** [zhenxun-org/nonebot_plugins_zhenxun_bot#54]
已经修改完dns为114.114.114.114
![image](https://user-images.githubusercontent.com/92635464/170168993-b8c5d103-1072-40a2-9f94-3761ba525e46.png)
重启bot的时候会提示下载模型但之后就没回复成功或者失败，看流量交换是没下载
在运行“更新模型列表”的时候报错如下：newplugins | Error downloading https://cdn.jsdelivr.net/gh/AkashiCoin/nonebot_plugin_mockingbird@master/nonebot_plugin_mockingbird/resource/model_list.json .. Error: [Errno 101] Network is unreachable

还有下载本地文件安装的我也试了但还是没反应，是文件夹放错了吗orz，求大佬邦邦
![image](https://user-images.githubusercontent.com/92635464/170169430-b946adf1-232c-4c99-956b-d810de2bc2bf.png)、
![image](https://user-images.githubusercontent.com/92635464/170169472-e066f2d0-4caf-4d0a-bcf0-ed94c8648264.png)

模型列表json也改好了
以下是报错（应该和其他人的一样）### 05-25 11:35:37 [ERROR] nonebot | Running matcher <Matcher from newplugins.mockingbird, type=message, priority=4, temp=False> failed.
Traceback (most recent call last):
  File "bot.py", line 21, in <module>
    nonebot.run()
  File "/usr/local/lib/python3.8/dist-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/usr/local/lib/python3.8/dist-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/usr/local/lib/python3.8/dist-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/home/zhenxun_bot/newplugins/mockingbird/__init__.py", line 166, in _
    record = await asyncio.get_event_loop().run_in_executor(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mockingbirdforuse/__init__.py", line 84, in synthesize
    raise Exception("Please set encoder path first")
Exception: Please set encoder path first
###

**Comment by milkasir** [comment]
重新全下了一遍文件和重启之后可用了
