### ISSUE TITLE
APEX战绩查询插件导入报错怎么解决

### ISSUE THREAD

**Issue by a930389426** [zhenxun-org/nonebot_plugins_zhenxun_bot#64]

**Comment by a930389426** [comment]
05-26 17:25:41 [ERROR] nonebot | Failed to import "ApexLegends-QQ-Robot-master"
Traceback (most recent call last):
  File "C:\zhenxun_bot-0.1.5.3\bot.py", line 15, in <module>
    nonebot.load_plugins("my_plugins")
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\administrator-c9Q8PpEX-py3.8\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\administrator-c9Q8PpEX-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 128, in load_all_plugins
    return set(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\administrator-c9Q8PpEX-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\administrator-c9Q8PpEX-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 106, in load_plugin
    module = importlib.import_module(
  File "c:\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\administrator-c9Q8PpEX-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 194, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\zhenxun_bot-0.1.5.3\my_plugins\ApexLegends-QQ-Robot-master\__init__.py", line 2, in <module>
    from .utils import *
  File "C:\zhenxun_bot-0.1.5.3\my_plugins\ApexLegends-QQ-Robot-master\utils.py", line 10, in <module>
    CONFIG = Config(CONFIG_PATH)
  File "C:\zhenxun_bot-0.1.5.3\my_plugins\ApexLegends-QQ-Robot-master\Config.py", line 7, in __init__
    self.__config = json.load(js_f)
  File "c:\python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "c:\python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "c:\python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Josef1999** [comment]
这个是因为先前的config.json中指向qq_eaID.json的路径末尾有多余的斜杠""，这个问题已经修复了，下载最新版的插件就行

**Comment by a930389426** [comment]
好的，谢谢
